if [ -f ~/.bash_aliases ]; then
. ~/.bash_aliases
fi

export BASH_SILENCE_DEPRECATION_WARNING=1

export CLICOLOR=1
export TERM=xterm-256color
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "

export LSCOLORS="ExFxBxDxCxegedabagacad"
alias ls='ls -GFh'

